In [1]:
import json
import os

# CONFIGURACIÓN DE LLAVE DE KAGGLE
USER_KAGGLE = "miguelcohuoavila"
TOKEN_KAGGLE = "KGAT_55e0a982de6adeb5ddef2906840d14b9"

data = {"username": USER_KAGGLE, "key": TOKEN_KAGGLE}

# Creación del archivo de configuración
with open('kaggle.json', 'w') as f:
    json.dump(data, f)

# Comandos de sistema para ubicar la llave en el directorio de seguridad del SO
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

print("¡Infraestructura de autenticación configurada con éxito!")

¡Infraestructura de autenticación configurada con éxito!

In [2]:
# Instalación de la librería oficial de Kaggle
!pip install -q kaggle

# Descarga del dataset de reseñas de Google Play
!kaggle datasets download -d lava18/google-play-store-apps

# Descompresión de los archivos
import zipfile
with zipfile.ZipFile("google-play-store-apps.zip", "r") as zip_ref:
    zip_ref.extractall("data_playstore")

print("Dataset descargado y listo en la carpeta 'data_playstore'")

Dataset URL: https://www.kaggle.com/datasets/lava18/google-play-store-apps
License(s): CC-BY-SA-4.0
Downloading google-play-store-apps.zip to /content
  0% 0.00/1.94M [00:00<?, ?B/s]
100% 1.94M/1.94M [00:00<00:00, 914MB/s]
Dataset descargado y listo en la carpeta 'data_playstore'

In [4]:
import os
import pandas as pd

# Listar el contenido de la carpeta 'data_playstore'
print("Contenido de la carpeta 'data_playstore':")
print(os.listdir("data_playstore"))

# Asumiendo que hay un archivo CSV llamado 'googleplaystore.csv' o similar
# Puedes ajustar el nombre del archivo si es diferente
try:
    df = pd.read_csv("data_playstore/googleplaystore.csv")
    print("\nDataFrame creado con éxito. Primeras 5 filas:")
    print(df.head())
except FileNotFoundError:
    print("\nError: No se encontró el archivo 'googleplaystore.csv' en la carpeta 'data_playstore'.")
    print("Por favor, verifica el nombre del archivo y la ruta.")
except Exception as e:
    print(f"\nOcurrió un error al cargar el dataset: {e}")

Contenido de la carpeta 'data_playstore':
['googleplaystore_user_reviews.csv', 'googleplaystore.csv', 'license.txt']

DataFrame creado con éxito. Primeras 5 filas:
                                                 App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1
1                                Coloring book moana  ART_AND_DESIGN     3.9
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3

  Reviews  Size     Installs  Type Price Content Rating  \
0     159   19M      10,000+  Free     0       Everyone
1     967   14M     500,000+  Free     0       Everyone
2   87510  8.7M   5,000,000+  Free     0       Everyone
3  215644   25M  50,000,000+  Free     0           Teen
4     967  2.8M     100,000+  Free     0       Everyone

                      Genres      Last Updated         Current Ver  \
0               Art & Design   January 7, 2018               1.0.0
1  Art & Design;Pretend Play  January 15, 2018               2.0.0
2               Art & Design    August 1, 2018               1.2.4
3               Art & Design      June 8, 2018  Varies with device
4    Art & Design;Creativity     June 20, 2018                 1.1

    Android Ver
0  4.0.3 and up
1  4.0.3 and up
2  4.0.3 and up
3    4.2 and up
4    4.4 and up

### Slicing de Filas

Puedes seleccionar rangos de filas utilizando `iloc` (por índice numérico) o `loc` (por etiqueta de índice, si la tuvieras).

**Ejemplo con `iloc` (primeras 5 filas):**

In [15]:
print("Primeras 5 filas del DataFrame (iloc):")
display(df.iloc[0:6])

Primeras 5 filas del DataFrame (iloc):

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
5,Paper flowers instructions,ART_AND_DESIGN,4.4,167,5.6M,"50,000+",Free,0,Everyone,Art & Design,"March 26, 2017",1.0,2.3 and up

**Ejemplo con `iloc` (filas 10 a 14):**

In [6]:
print("Filas 10 a 14 del DataFrame (iloc):")
display(df.iloc[10:15])

Filas 10 a 14 del DataFrame (iloc):

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10,Text on Photo - Fonteee,ART_AND_DESIGN,4.4,13880,28M,"1,000,000+",Free,0,Everyone,Art & Design,"October 27, 2017",1.0.4,4.1 and up
11,Name Art Photo Editor - Focus n Filters,ART_AND_DESIGN,4.4,8788,12M,"1,000,000+",Free,0,Everyone,Art & Design,"July 31, 2018",1.0.15,4.0 and up
12,Tattoo Name On My Photo Editor,ART_AND_DESIGN,4.2,44829,20M,"10,000,000+",Free,0,Teen,Art & Design,"April 2, 2018",3.8,4.1 and up
13,Mandala Coloring Book,ART_AND_DESIGN,4.6,4326,21M,"100,000+",Free,0,Everyone,Art & Design,"June 26, 2018",1.0.4,4.4 and up
14,3D Color Pixel by Number - Sandbox Art Coloring,ART_AND_DESIGN,4.4,1518,37M,"100,000+",Free,0,Everyone,Art & Design,"August 3, 2018",1.2.3,2.3 and up

### Slicing de Columnas

Puedes seleccionar una o varias columnas utilizando sus nombres.

**Ejemplo seleccionando la columna 'App' y 'Category':**

In [7]:
print("Columnas 'App' y 'Category':")
display(df[['App', 'Category']].head())

Columnas 'App' y 'Category':

                                                 App        Category
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN
1                                Coloring book moana  ART_AND_DESIGN
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN
3                              Sketch - Draw & Paint  ART_AND_DESIGN
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN

### Slicing Combinado (Filas y Columnas)

También puedes combinar el slicing para seleccionar un rango de filas y un rango de columnas.

**Ejemplo: primeras 3 filas y columnas 'App' y 'Rating':**

In [8]:
print("Primeras 3 filas y columnas 'App', 'Rating':")
display(df.loc[0:2, ['App', 'Rating']])

Primeras 3 filas y columnas 'App', 'Rating':

                                                 App  Rating
0     Photo Editor & Candy Camera & Grid & ScrapBook     4.1
1                                Coloring book moana     3.9
2  U Launcher Lite – FREE Live Cool Themes, Hide ...     4.7

### Slicing con Índices Negativos (Últimas Filas)

Puedes usar índices negativos con `iloc` para seleccionar filas desde el final del DataFrame. Por ejemplo, `df.iloc[-5:]` te dará las últimas 5 filas.

In [12]:
print("Últimas 5 filas del DataFrame (iloc con índices negativos):")
display(df.iloc[-5:])

Últimas 5 filas del DataFrame (iloc con índices negativos):

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

### Slicing de Filas y Columnas No Consecutivas (con Listas de Índices)

Si necesitas seleccionar filas y/o columnas que no son contiguas, puedes pasar listas de índices a `iloc`. Por ejemplo, para seleccionar las filas 0, 2 y 5, y las columnas 1 y 3:

In [13]:
print("Filas 0, 2, 5 y columnas 1, 3 (iloc con listas de índices):")
display(df.iloc[[0, 2, 5], [1, 3]])

Filas 0, 2, 5 y columnas 1, 3 (iloc con listas de índices):

         Category Reviews
0  ART_AND_DESIGN     159
2  ART_AND_DESIGN   87510
5  ART_AND_DESIGN     167

### Slicing Condicional (Filtrado por Valor de Columna)

Una de las formas más potentes de seleccionar datos es usando condiciones lógicas. Con `loc`, puedes filtrar filas basándote en el valor de una columna y luego seleccionar las columnas que te interesan. Por ejemplo, para obtener las apps con una 'Rating' mayor a 4.5, mostrando solo las columnas 'App' y 'Rating':

In [14]:
print("Apps con Rating > 4.5 (slicing condicional):")
display(df.loc[df['Rating'] > 4.5, ['App', 'Rating']].head())

Apps con Rating > 4.5 (slicing condicional):

                                                  App  Rating
2   U Launcher Lite – FREE Live Cool Themes, Hide ...     4.7
9                       Kids Paint Free - Drawing Fun     4.7
13                              Mandala Coloring Book     4.6
16       Photo Designer - Write your name with shapes     4.7
19                                       ibis Paint X     4.6

### Slicing `[:]` (Todas las Filas y Todas las Columnas)

El formato `df.iloc[:, :]` selecciona todas las filas y todas las columnas de tu DataFrame. Es equivalente a mostrar el DataFrame completo, aunque usaremos `.head()` para ver solo las primeras filas por eficiencia.

In [9]:
print("Todas las filas y columnas (primeras 5 filas):")
display(df.iloc[:, :].head())

Todas las filas y columnas (primeras 5 filas):

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

### Slicing `[3, :]` (Fila en Índice 3 y Todas las Columnas)

El formato `df.iloc[3, :]` selecciona la fila específica en el índice numérico `3` y todas sus columnas correspondientes. Recuerda que el indexado es base 0, por lo que `3` es la cuarta fila.

In [10]:
print("Fila en el índice 3 y todas sus columnas:")
display(df.iloc[3, :])

Fila en el índice 3 y todas sus columnas:

App               Sketch - Draw & Paint
Category                 ART_AND_DESIGN
Rating                              4.5
Reviews                          215644
Size                                25M
Installs                    50,000,000+
Type                               Free
Price                                 0
Content Rating                     Teen
Genres                     Art & Design
Last Updated               June 8, 2018
Current Ver          Varies with device
Android Ver                  4.2 and up
Name: 3, dtype: object

### Slicing `[:, 9]` (Todas las Filas y Columna en Índice 9)

El formato `df.iloc[:, 9]` selecciona todas las filas y la columna específica que se encuentra en el índice numérico `9`. Veremos las primeras 5 filas de esta columna.

In [11]:
print("Todas las filas de la columna en el índice 9 (primeras 5 filas):")
display(df.iloc[:, 9].head())

Todas las filas de la columna en el índice 9 (primeras 5 filas):

0                 Art & Design
1    Art & Design;Pretend Play
2                 Art & Design
3                 Art & Design
4      Art & Design;Creativity
Name: Genres, dtype: object